services:
  bot:
    container_name: tg_bot
    build: .
    volumes:
      - .:/usr/src/app
    command: bash -c "alembic upgrade head && python -m app.bot.main"
    env_file:
      - .env
    depends_on:
      - database
  
  database:
    container_name: tg_bot_database
    image: postgres:15
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - ${POSTGRES_PORT}

volumes:
  database:
