"""Add cascade deletes to categories and subcategories

Revision ID: 948e50ae53b6
Revises: d1c3dbe89dbd
Create Date: 2025-05-01 17:16:44.425981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948e50ae53b6'
down_revision: Union[str, None] = 'd1c3dbe89dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('content_items_subcategory_id_fkey', 'content_items', type_='foreignkey')
    op.create_foreign_key(None, 'content_items', 'subcategories', ['subcategory_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('subcategories_category_id_fkey', 'subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'subcategories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.create_foreign_key('subcategories_category_id_fkey', 'subcategories', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.create_foreign_key('content_items_subcategory_id_fkey', 'content_items', 'subcategories', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###
